### PR TITLE
Add support for Kubernetes plugin

### LINKED ISSUE #37: Add support for Kubernetes plugin
Hi,
It would be great if we could use pipeline-as-yaml-plugin to describe a pipeline which uses the kubernetes agent. At the moment it doesn't seem to be possible.
Something like:

```
pipeline:
  agent:
    kubernetes:
      cloud: mystack
      yaml: >
        apiVersion: v1
        kind: Pod
        spec:
            imagePullSecrets:
            - name: my-creds
            containers:
            - name: ubuntu
              image: myimage:1.1
              command: ['sleep', 'infinity']
              tty: true
              imagePullPolicy: Always'''
    stages:
      - stage: Test
        steps: echo "Hello world"
```

I've tried to run the pipeline above through the _conversion tool_ provided by the plugin and it _almost_ worked. The problem is that they "yaml" key's value gets converted in a string with single quotes, which doesn't work with multiline strings such as the pod definition above.
I reckon if the plugin was able to wrap the value of the `yaml` key in a multiline string (e.g. '''string''') that would work

### PR DESCRIPTION
**Pull request by lengyf**
Fix #37

### CODE REVIEW

**Comment by aytuncbeken** [comment]
Hi @lengyf , 
thanks for contribution. 
Could you please test with the code block which you mentioned in your issue ? 
```>
        apiVersion: v1
        kind: Pod
        spec:
            imagePullSecrets:
            - name: my-creds
            containers:
            - name: ubuntu
              image: myimage:1.1
              command: ['sleep', 'infinity']
              tty: true
              imagePullPolicy: Always'''```

**Comment by ferrucciobongianni** [comment]
@lengyf thanks a lot for fixing this! :) I'm looking forward to this patch being released.

**Comment by ferrucciobongianni** [comment]
@lengyf I have tested the plugin in my environment and it seems to work correctly. Thanks!

**Comment by aytuncbeken** [comment]
Hi @lengyf ,

Thanks for the updates. I will release this version as soon as possible.

**Comment by aytuncbeken** [comment]
Released with 0.16-rc version. 
Thank you for contribution @lengyf  @ferrucciobongianni

**Pull request merged**
